# Generated by Django 4.1.3 on 2022-11-03 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=45, verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.FloatField(default=0, verbose_name='баланс пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='transactions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction_manager.transaction', verbose_name='транзакции'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction_manager.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.FloatField(default=0, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата создания'),
        ),
    ]
